site_name: WebGBAT Docs
pages:
- WebGBAT Glossary: index.md
- WebGBAT User Guide: webGBATUserGuide.md
- WebGOAT User Guide: userguide.md
extra_css:
    - css/main.css
extra_javascript:
    - js/main.js
